# -*- coding: utf-8 -*-
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from c6_sweep_common import run

RUN_MODE_DEFAULT = "ask"
TEST_POINT_COUNT = 3
START_NM = 0.0
END_NM = 40.0
STEP_NM = 5.0
CUT_DEPTH_START_NM = START_NM
CUT_DEPTH_STOP_NM = END_NM
CUT_DEPTH_STEP_NM = STEP_NM
AUTO_CUT_DEPTH_STEP = True
TARGET_SCAN_POINTS = 9
CUT_DEPTH_STEP_MIN_NM = 2.5
CUT_DEPTH_STEP_MAX_NM = 8.0
CUT_WIDTH_NM = 60.0
SIMULATION_TIME_FS = 10000.0
SIMULATION_TIME_S = SIMULATION_TIME_FS * 1e-15
AUTO_SHUTOFF_MIN = 1e-12
MESH_ACCURACY = 2
DT_STABILITY_FACTOR = 0.8

CONFIG = dict(
    STRUCTURE_ROOT=r"H:\FDTD outcome\struct\群论_struct\C6对称结构\六裂缝环",
    STRUCTURE_CN_NAME="六裂缝环",
    SAFE_NAME="six_slit_ring",
    LUMERICAL_ROOT=r"D:\Program Files\Lumerical\v202",
    ASCII_WORK_ROOT=r"H:\FDTD_CodeX\fdtd_ascii_work",
    PERTURBATION_NAME="单点缺口扰动",
    GROUP_PATH="C6 -> C1",
    OBJECT_NAME="air_slit",
    OPERATION="insert_cut",
    OPERATION_DESCRIPTION="在外环右侧额外插入一个 etch 矩形缺口，扫描缺口向内切入深度。",
    TARGET_INDICES=(1,),
    VALUE_NAME="cut_depth",
    SCAN_LABEL="single_cut",
    SCAN_START_NM=CUT_DEPTH_START_NM,
    SCAN_STOP_NM=CUT_DEPTH_STOP_NM,
    SCAN_STEP_NM=CUT_DEPTH_STEP_NM,
    AUTO_SCAN_STEP=AUTO_CUT_DEPTH_STEP,
    TARGET_SCAN_POINTS=TARGET_SCAN_POINTS,
    SCAN_STEP_MIN_NM=CUT_DEPTH_STEP_MIN_NM,
    SCAN_STEP_MAX_NM=CUT_DEPTH_STEP_MAX_NM,
    CUT_WIDTH_NM=CUT_WIDTH_NM,
    TEST_POINT_COUNT=TEST_POINT_COUNT,
    RUN_MODE_DEFAULT=RUN_MODE_DEFAULT,
    SIMULATION_TIME_FS=SIMULATION_TIME_FS,
    SIMULATION_TIME_S=SIMULATION_TIME_S,
    AUTO_SHUTOFF_MIN=AUTO_SHUTOFF_MIN,
    MESH_ACCURACY=MESH_ACCURACY,
    DT_STABILITY_FACTOR=DT_STABILITY_FACTOR,
    T_MONITOR_NAME="T",
)

if __name__ == "__main__":
    run(CONFIG)
