# -*- coding: utf-8 -*-
from pathlib import Path
import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from c6_sweep_common import run

RUN_MODE_DEFAULT = "ask"
TEST_POINT_COUNT = 3
OPPOSITE_ARM_INDEX = 1
START_NM = 70.0
END_NM = 150.0
STEP_NM = 10.0
ARM_WIDTH_START_NM = START_NM
ARM_WIDTH_STOP_NM = END_NM
ARM_WIDTH_STEP_NM = STEP_NM
AUTO_ARM_WIDTH_STEP = True
TARGET_SCAN_POINTS = 9
ARM_WIDTH_STEP_MIN_NM = 5.0
ARM_WIDTH_STEP_MAX_NM = 15.0
SIMULATION_TIME_FS = 10000.0
SIMULATION_TIME_S = SIMULATION_TIME_FS * 1e-15
AUTO_SHUTOFF_MIN = 1e-12
MESH_ACCURACY = 2
DT_STABILITY_FACTOR = 0.8

CONFIG = dict(
    STRUCTURE_ROOT=r"H:\FDTD outcome\struct\群论_struct\C6对称结构\六臂星",
    STRUCTURE_CN_NAME="六臂星",
    SAFE_NAME="six_arm_star",
    LUMERICAL_ROOT=r"D:\Program Files\Lumerical\v202",
    ASCII_WORK_ROOT=r"H:\FDTD_CodeX\fdtd_ascii_work",
    PERTURBATION_NAME="对臂变化扰动",
    GROUP_PATH="C6 -> C2",
    OBJECT_NAME="Si_arm",
    OPERATION="set_x_span",
    OPERATION_DESCRIPTION="改变一个穿心 Si_arm 矩形宽度；该矩形正好代表一对相对臂。",
    TARGET_INDICES=(OPPOSITE_ARM_INDEX,),
    VALUE_NAME="arm_width",
    SCAN_LABEL="opposite_arm_width",
    SCAN_START_NM=ARM_WIDTH_START_NM,
    SCAN_STOP_NM=ARM_WIDTH_STOP_NM,
    SCAN_STEP_NM=ARM_WIDTH_STEP_NM,
    AUTO_SCAN_STEP=AUTO_ARM_WIDTH_STEP,
    TARGET_SCAN_POINTS=TARGET_SCAN_POINTS,
    SCAN_STEP_MIN_NM=ARM_WIDTH_STEP_MIN_NM,
    SCAN_STEP_MAX_NM=ARM_WIDTH_STEP_MAX_NM,
    TEST_POINT_COUNT=TEST_POINT_COUNT,
    RUN_MODE_DEFAULT=RUN_MODE_DEFAULT,
    SIMULATION_TIME_FS=SIMULATION_TIME_FS,
    SIMULATION_TIME_S=SIMULATION_TIME_S,
    AUTO_SHUTOFF_MIN=AUTO_SHUTOFF_MIN,
    MESH_ACCURACY=MESH_ACCURACY,
    DT_STABILITY_FACTOR=DT_STABILITY_FACTOR,
    T_MONITOR_NAME="T",
)

if __name__ == "__main__":
    run(CONFIG)
